### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by N6RFM** [ASU-cubesat/phxsat-gsw-public#1]
Executing the program give the following error - "There was an error creating the child process for this terminal Failed to execute child process “./csp-client” (No such file or directory)."  

The link to the directory libcsp @ b8cdb34 seems broken (or no content), thus it appears that the libcsp module is not collected during the git clone step.  Also, the link url = https://github.com/ASU-cubesat/phxsat-gsw-host.git in the .gitmodules step is not working.

Thanks,  Bob N6RFM

**Comment by vivekjc** [comment]
Hello N6RFM, 

You would need to pull the submodules after cloning the repository. You could use the following command to clone the submodules.
```
git submodule update --init
```

I have updated the readme with some more instructions that addresses this issue. You might also need to change the device you are using. Instructions also included in readme.

**Comment by K4KDR** [comment]
Thank you for the additional instruction on this issue.

Strangely, that command results in a request for a GITHUB login, which I am reluctant to provide blindly:

```
k4kdr@:~/phxsat-gsw-public$ git submodule update --init
Cloning into 'libcsp'...
Username for 'https://github.com': K4KDR
Password for 'https://K4KDR@github.com': 
```

... is this repository not public?

Many thanks.

-Scott,  K4KDR

**Comment by N6RFM** [comment]
Unfortunately, the same credentials I use to log onto GitHub do not work.  Why is this repository not public?  Thanks.

**Comment by vivekjc** [comment]
We have some proprietary code that is on a private repo. It is shared with a host repo so that we can maintain issues while keeping some of the code private. The issue likely occurred because our host repo that links the two was not made public. This has been changed now. Give it a try!

**Comment by K4KDR** [comment]
The submodule update now works - thanks very much!

```
k4kdr@:~/phxsat-gsw-public$ git submodule update --init
Cloning into 'libcsp'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 157 (delta 40), reused 154 (delta 40), pack-reused 0
Receiving objects: 100% (157/157), 277.06 KiB | 153.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.
Checking connectivity... done.
Submodule path 'libcsp': checked out 'b8cdb3439f5d16504103856a1d079f6fadb92ee4'
```

**Comment by N6RFM** [comment]
Thanks vivekjc. working here also

**Comment by sarahsrogers** [comment]
awesome! I'll close this issue out, since it's working, but if anything else comes up, please feel free to reopen/post a new issue.
