### ISSUE TITLE
Source/Dest Call Signs not transmitting as indicated

### ISSUE THREAD

**Issue by K4KDR** [ASU-cubesat/phxsat-gsw-public#10]
Please forgive me starting a separate issue from Bob's on this topic, but while that thread included compile issues, here I wish to question one specific behavior.

After editing src/main.c to include the desired SOURCE & DEST call signs, the application starts up exactly as you would expect:

```
************************************************
*****    PHOENIX CUBESAT GROUND STATION    *****
********** Arizona State University ************
***** School of Earth & Space Exploration ******
*************** Public Release *****************
************************************************
Source callsign has been set to K4KDR
Destination callsign has been set to WJ2XOY
Level 2: value 1
Using TNC at /tmp/kisstnc
Starting CLI...
Starting Server...
Enter a command: (or type 'help')
└─ > Binding socket 0x60e570 to port 32
ping 2
Ping node 2 in -1ms
└─ > 
```

... however, please note that the indicated call signs are NOT what is actually transmitted.  The following was transmitted:
```
------
 dest    KI7OOY  0 c/r=0 res=3 last=0
 source  WJ2XOY  0 c/r=0 res=3 last=1
  000:  96 92 6e 9e 9e b2 60 ae 94 64 b0 9e b2 61 03 f0  ..n...`..d...a..
  010:  94 20 79 01 00 01 02 03 04 05 06 07 08 09 0a 0b  . y.............
  020:  0c 0d 0e 0f 10 11 12 13 cc 79 eb e6              .........y..
------
```

Thank you and best wishes for successful deployment tomorrow!

**Comment by vivekjc** [comment]
Apologies for the bug. 

This should be fixed now and tested. Please test it at your end and let us know if any other issues remain.

Thank you for testing out our software and hope you have a great rest of the day!

**Comment by vivekjc** [comment]
Closing this issue for now, but please feel free to reopen if the issue still remains.
