### ISSUE TITLE
Config File aided startup sequence

### ISSUE THREAD

**Issue by vivekjc** [ASU-cubesat/phxsat-gsw-public#11]
The latest commit adds a config file to the startup sequence. This allows user to enter the source, destination callsigns and have it read on subsequent startup sequence.

The behavior of this functionality can be summarized as below:
1. On first startup the PHX Ground Station Client asks for a Source and Destination Callsign and saves this to `config.phx` file in the root folder.
2. On subsequent startup, if this file is present the program loads the information and presents it to the user. At this point the user can either confirm using these details or provide new details. This is handled by either entering a 'Y' or 'N'.

Future release would include selecting the TNC channel.

**Comment by N6RFM** [comment]
Thanks Vivek.  Working!
