### ISSUE TITLE
Request that uses be allowed to modify the source and destination callsigns

### ISSUE THREAD

**Issue by N6RFM** [ASU-cubesat/phxsat-gsw-public#6]
Currently, ping 2 shows KI007Y as both source and destination.  Please allow the user to modify each of these call signs, e.g, N6RFM-6 > WJ2XOY.

Thanks,

Bob
N6RFM

**Comment by vivekjc** [comment]
Thanks for bringing this up. We are working on a method to enable users to enter their callsign upon startup.

Will post the instructions/details once it is uploaded to git.

**Comment by N6RFM** [comment]
Thank you, vivekjc.

**Comment by N6RFM** [comment]
Hi Vivek,
Just did a git pull.  Appreciate working on adding callsign.  But Make fails -
main.c:(.text+0xd8): undefined reference to `ax25_dest_src_bytes'
main.c:(.text+0x346): undefined reference to `ax25_dest_src_bytes'
main.c:(.text+0x35b): undefined reference to `ax25_dest_src_bytes'
main.c:(.text+0x573): undefined reference to `ax25_dest_src_bytes'
main.c:(.text+0x585): undefined reference to `ax25_dest_src_bytes'
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'all' failed
make: *** [all] Error 1

Thanks,

Bob

**Comment by vivekjc** [comment]
The callsign change has been made, but will be improved by adding a config file. Closing this issue for now, and we can track additional progress in a config file issue
