### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by N6RFM** [ASU-cubesat/phxsat-gsw-public#7]
Hi Vivek,

Just did a git pull. Appreciate your working on adding callsign. 

But Make fails -
main.c:(.text+0xd8): undefined reference to ax25_dest_src_bytes' main.c:(.text+0x346): undefined reference to ax25_dest_src_bytes'
main.c:(.text+0x35b): undefined reference to ax25_dest_src_bytes' main.c:(.text+0x573): undefined reference to ax25_dest_src_bytes'
main.c:(.text+0x585): undefined reference to `ax25_dest_src_bytes'
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'all' failed
make: *** [all] Error 1

Thanks,

Bob

**Comment by sarahsrogers** [comment]
Hi, Bob,

The edits to add the AX25 callsign info were added to our host branch, as this functionality is shared between our public and private code. To update your code with these changes, please try the following commands in order. This is what worked for me on a fresh system, at least. Let me know if this works for you.

1. `cd libcsp` 
2. `git checkout master`
3. `cd ..`
4. `make`
5. `sh quickMake.sh`

You should get a startup that looks similar to the image below, which will allow you to enter both the source and destination callsign info

![image](https://user-images.githubusercontent.com/15206856/74213214-7d84ae80-4c55-11ea-8868-48f17a5ed6f2.png)

**Comment by N6RFM** [comment]
Hi Sarah and Vivek,

It works!  Thanks both.  Good luck with the deployment tomorrow.  Will be listening.  HI HI

If you'd like to give me access to the wiki page here, I'd be happy to create a page describing how to get the GS working with Direwolf.

73,
Bob

**Comment by sarahsrogers** [comment]
Thanks Bob! I'm glad to hear that worked for you :)

We have made the following document to help people configure direwolf and gqrx, as well as some additional instructions on how to set up our ground station software with direwolf as well. do you think this would suffice, or is there anything you feel we should add? 

https://docs.google.com/document/d/1TnPlaMJsSXvp0Ddgf6FEaB0jit0optRtFlt9bA049rg/edit?usp=sharing

**Comment by N6RFM** [comment]
Hi Sarah,

Nice document.  Thanks sharing!

Several suggestions -

GQRX- 

Advise users to first try using one of the binary images from the GQRX downloads page.
GQRX can be tricky to install properly from source, even when using the PPA approach for Ubuntu based OS's.  

When streaming from GQRX over UDP, the UDP button must be toggled into the "on" or greyed out state.  While your screenshot shows this, you might want to mention this in the text.  Even GQRX veterans overlook this at times. Don't ask how I know!

Direwolf -

While modifying the main.c code works, it's not necessary for users to edit this code to connect to the virtual tnc.  TKS John WB2OSZ  (author of Direwolf) for pointing this out. 

Instead, just add /tmp/kisstnc by editing the quickMake.sh script like this -
 
gnome-terminal --title="Command Terminal" --geometry 88x55+0+0 -e "./csp-client /tmp/kisstnc"

As an alternative to direwolf -r 48000 -B 9600 udp:7355 -p (which is used for GQRX) , Direwolf users may create and edit unique config files which includes specifics for their own installation.  These are all described in the Direwolf user manual.  

Information such as audio rate (ARATE 48000), modem choice (MODEM 9600), and udp (ADEVICE udp:7355 default) may be specified in a phxsat.conf file, and the -p switch enables the pseudo kisstnc mode.  Then run Direwolf with the command line direwolf -c phxsat.conf -p.

Thanks again es 73!
Bob
N6RFM

**Comment by vivekjc** [comment]
Closing this issue, and will make a new issue to address implementing a config file
