### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by N6RFM** [ASU-cubesat/phxsat-gsw-public#8]
Just an FYI - when running quickMake.sh under Mint 19.2/Ubuntu 18.04 
(not sure if you are seeing this on your installation)

src/main.c:97:31: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]
             printf("\x1B[31m%ld Invalid character(s) detected in callsign. Try Again.\n \x1B[0m",invalid_char);
                             ~~^
                             %d
src/main.c:139:31: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]
             printf("\x1B[31m%ld Invalid character(s) detected in callsign. Try Again.\n \x1B[0m",invalid_char);
                             ~~^
                             %d
src/server.c: In function ‘debug_task’:
src/server.c:45:50: warning: unused variable ‘year’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
                                                  ^~~~
src/server.c:45:43: warning: unused variable ‘month’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
                                           ^~~~~
src/server.c:45:38: warning: unused variable ‘day’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
                                      ^~~
src/server.c:45:29: warning: unused variable ‘seconds’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
                             ^~~~~~~
src/server.c:45:20: warning: unused variable ‘minutes’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
                    ^~~~~~~
src/server.c:45:13: warning: unused variable ‘hours’ [-Wunused-variable]
         int hours, minutes, seconds, day, month, year;
             ^~~~~

**Comment by vivekjc** [comment]
Thanks for pointing this out. 

The warnings should now be fixed in the latest commit labeled "Fixed Compilation Warnings"

Regards
Vivek

**Comment by vivekjc** [comment]
Closing this out for now, but please feel free to reopen if needed.
